BOX_IMAGE = "ubuntu/bionic64"
BOX_VERSION = "20220805.0.0"

N = 2

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.define "hk8s-m" do |master|
        master.vm.box = BOX_IMAGE
        master.vm.box_version = BOX_VERSION
        master.vm.network "private_network", ip: "192.168.56.50"
        master.vm.hostname = "hk8s-m"
        master.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--groups", "/hk8s"]
          v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
          v.cpus = 2
          v.memory = 2048
          v.linked_clone = true
        end
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/master-playbook.yaml"
            ansible.extra_vars = {
                ansible_python_interpreter: "/usr/bin/python3",
                node_ip: "192.168.56.50",
            }
        end
    end

    (1..N).each do |i|
        config.vm.define "hk8s-w#{i}" do |worker|
            worker.vm.box = BOX_IMAGE
            worker.vm.box_version = BOX_VERSION
            worker.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            worker.vm.hostname = "hk8s-w#{i}"
            worker.vm.provider "virtualbox" do |v|
              v.customize ["modifyvm", :id, "--groups", "/hk8s"]
              v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
              v.cpus = 2
              v.memory = 2048
              v.linked_clone = true
            end
            worker.vm.provision "ansible" do |ansible|
                ansible.playbook = "playbooks/worker-playbook.yaml"
                ansible.extra_vars = {
                    ansible_python_interpreter: "/usr/bin/python3",
                    node_ip: "192.168.56.#{i + 10}",
                }
            end
        end
    end
end
